# Copyright 2024 Tobias Senti
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

on: [push, pull_request]
jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Check setup
        run: make .setup

  yamllint:
    runs-on: self-hosted
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        run: make yamllint

  tclint:
    runs-on: self-hosted
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Run tclint
        run: make tclint

  pylint:
    runs-on: self-hosted
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Run pylint
        run: make pylint

  jsonlint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run jsonlint
        run: make jsonlint

  veriloglint:
    runs-on: self-hosted
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Run veriloglint
        run: make veriloglint

  basic_tests:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Generate pdk
        run: make pdk/.pdk
      - name: Create Merge Cells
        run: make gen_pdk

  pdk_tcllint:
    runs-on: self-hosted
    needs: basic_tests
    steps:
      - uses: actions/checkout@v4
      - name: Run gen_pdk
        run: make gen_pdk
      - name: Run tclint after gen_pdk
        run: make tclint

  pdk_veriloglint:
    runs-on: self-hosted
    needs: basic_tests
    steps:
      - uses: actions/checkout@v4
      - name: Run gen_pdk
        run: make gen_pdk
      - name: Run veriloglint after gen_pdk
        run: make veriloglint
