# Copyright 2024 Tobias Senti
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

on: [push, pull_request]
jobs:
  python_setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Check python setup
        run: make .python_setup

  yamllint:
    runs-on: self-hosted
    needs: python_setup
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        run: make yamllint

  tclint:
    runs-on: self-hosted
    needs: python_setup
    steps:
      - uses: actions/checkout@v4
      - name: Run tclint
        run: make tclint

  pylint:
    runs-on: self-hosted
    needs: python_setup
    steps:
      - uses: actions/checkout@v4
      - name: Run pylint
        run: make pylint

  jsonlint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run jsonlint
        run: make jsonlint

  basic_tests:
    runs-on: self-hosted
    needs: python_setup
    steps:
      - name: Generate pdk
        run: make pdk/.pdk
      - name: Create Merge Cells
        run: make gen_pdk
